apiVersion: batch/v1
kind: Job
metadata:
  name: pytest-job
  namespace: test
spec:
  template:
    spec:
      containers:
        - name: pytest
          image: pytest-sas-sdet:ci
          imagePullPolicy: IfNotPresent
          env:
            - name: BASE_URL
              value: "http://api-service:8090"
            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: username
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: password
          command: ["pytest", "--maxfail=1", "--disable-warnings", "-v"]
      restartPolicy: Never
  backoffLimit: 0
