apiVersion: batch/v1
kind: Job
metadata:
  name: pytest-job
  namespace: test
spec:
  template:
    spec:
      containers:
        - name: pytest
          image: pytest-sas-sdet:ci
          imagePullPolicy: Never
          env:
            - name: BASE_URL
              value: "http://api-service:8090"
            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: username
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: password
          command: ["pytest", "-v", "--capture=no", "--html=reports/pytest-report.html", "--self-contained-html", "--log-file=reports/all-tests.log", "-m", "regression"]
          volumeMounts:
            - name: reports
              mountPath: /reports

      volumes:
        - name: reports
          emptyDir: {}
      restartPolicy: Never

  backoffLimit: 0
