name: Run SDET Pytest API Automation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: Run Pytest Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      # Install dependencies
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      # Start the API Docker container
      - name: Run API container
        run: |
          docker run -d -p 8090:8080 --name api-server callumhunter/sas_sdet_interview:latest
          sleep 5
      # Wait until the API is ready
      - name: Wait for API
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:8090/playerName; then
              echo "API is up!"
              break
            fi
            echo "Waiting for API..."
            sleep 2
          done
      # Run tests with pytest and generate HTML report
      - name: Run Pytest
        run: |
          mkdir -p reports
          pytest -v --capture=no --html=reports/pytest-report.html --self-contained-html --log-file=reports/all-tests.log -m regression
      # Upload HTML report as artifact(viewable in GitHub Actions)
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/pytest-report.html
      # Upload Test Logs
      - name: Upload Individual test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: reports/logs/*.log
      # Upload All Test Logs
      - name: Upload All tests log
        uses: actions/upload-artifact@v4
        with:
          name: all-tests.log
          path: reports/all-tests.log
      # Stop and remove the APi container
      - name: Cleanup Docker container
        run: |
          docker stop api-server
          docker rm api-server



